export const VENUE_IMAGE_MAP = {
  bj1: ['/images/venues/bj1_2.jpg'],
  bj2: ['/images/venues/bj2_1.jpg', '/images/venues/bj2_3.jpg'],
  bj3: ['/images/venues/bj3_1.jpg', '/images/venues/bj3_2.jpg'],
  bj4: ['/images/venues/bj4_1.jpg', '/images/venues/bj4_3.jpg'],
  bj5: ['/images/venues/bj5_2.jpg'],
  bj6: ['/images/venues/bj6_1.jpg', '/images/venues/bj6_2.jpg', '/images/venues/bj6_3.jpg'],
  bj7: ['/images/venues/bj7_1.jpg', '/images/venues/bj7_2.jpg', '/images/venues/bj7_3.jpg'],
  cd1: ['/images/venues/cd1_2.jpg', '/images/venues/cd1_3.jpg'],
  cd2: ['/images/venues/cd2_1.jpg', '/images/venues/cd2_2.jpg'],
  cq1: ['/images/venues/cq1_2.jpg', '/images/venues/cq1_3.jpg'],
  cq2: ['/images/venues/cq2_1.jpg', '/images/venues/cq2_3.jpg'],
  cq3: ['/images/venues/cq3_1.jpg', '/images/venues/cq3_3.jpg'],
  cs2: ['/images/venues/cs2_1.jpg', '/images/venues/cs2_2.jpg', '/images/venues/cs2_3.jpg'],
  cs3: ['/images/venues/cs3_1.jpg', '/images/venues/cs3_2.jpg', '/images/venues/cs3_3.jpg'],
  dg1: ['/images/venues/dg1_2.jpg'],
  dl2: ['/images/venues/dl2_1.jpg', '/images/venues/dl2_2.jpg'],
  dl3: ['/images/venues/dl3_2.jpg', '/images/venues/dl3_3.jpg'],
  fz1: ['/images/venues/fz1_1.jpg', '/images/venues/fz1_3.jpg'],
  gy1: ['/images/venues/gy1_1.jpg', '/images/venues/gy1_2.jpg', '/images/venues/gy1_3.jpg'],
  gz1: ['/images/venues/gz1_1.jpg', '/images/venues/gz1_2.jpg', '/images/venues/gz1_3.jpg'],
  gz2: ['/images/venues/gz2_1.jpg'],
  gz3: ['/images/venues/gz3_1.jpg', '/images/venues/gz3_2.jpg', '/images/venues/gz3_3.jpg'],
  gz4: ['/images/venues/gz4_1.jpg', '/images/venues/gz4_2.jpg', '/images/venues/gz4_3.jpg'],
  gz5: ['/images/venues/gz5_1.jpg', '/images/venues/gz5_2.jpg', '/images/venues/gz5_3.jpg'],
  gz6: ['/images/venues/gz6_1.jpg', '/images/venues/gz6_2.jpg', '/images/venues/gz6_3.jpg'],
  gz7: ['/images/venues/gz7_3.jpg'],
  hf1: ['/images/venues/hf1_1.jpg', '/images/venues/hf1_2.jpg', '/images/venues/hf1_3.jpg'],
  hrb1: ['/images/venues/hrb1_1.jpg', '/images/venues/hrb1_2.jpg', '/images/venues/hrb1_3.jpg'],
  hz1: ['/images/venues/hz1_1.jpg', '/images/venues/hz1_2.jpg', '/images/venues/hz1_3.jpg'],
  hz2: ['/images/venues/hz2_1.jpg', '/images/venues/hz2_2.jpg'],
  hz3: ['/images/venues/hz3_1.jpg'],
  jn1: ['/images/venues/jn1_1.jpg', '/images/venues/jn1_2.jpg', '/images/venues/jn1_3.jpg'],
  jn2: ['/images/venues/jn2_2.jpg', '/images/venues/jn2_3.jpg'],
  km1: ['/images/venues/km1_3.jpg'],
  nc1: ['/images/venues/nc1_1.jpg', '/images/venues/nc1_2.jpg', '/images/venues/nc1_3.jpg'],
  nj1: ['/images/venues/nj1_1.jpg', '/images/venues/nj1_2.jpg', '/images/venues/nj1_3.jpg'],
  nj3: ['/images/venues/nj3_1.jpg', '/images/venues/nj3_2.jpg', '/images/venues/nj3_3.jpg'],
  nn1: ['/images/venues/nn1_1.jpg', '/images/venues/nn1_3.jpg'],
  qd1: ['/images/venues/qd1_2.jpg', '/images/venues/qd1_3.jpg'],
  sh1: ['/images/venues/sh1_1.jpg', '/images/venues/sh1_2.jpg', '/images/venues/sh1_3.jpg'],
  sh2: ['/images/venues/sh2_2.jpg', '/images/venues/sh2_3.jpg'],
  sh3: ['/images/venues/sh3_3.jpg'],
  sh4: ['/images/venues/sh4_1.jpg', '/images/venues/sh4_2.jpg', '/images/venues/sh4_3.jpg'],
  sh5: ['/images/venues/sh5_2.jpg', '/images/venues/sh5_3.jpg'],
  sh6: ['/images/venues/sh6_1.jpg', '/images/venues/sh6_2.jpg', '/images/venues/sh6_3.jpg'],
  sh7: ['/images/venues/sh7_1.jpg', '/images/venues/sh7_2.jpg', '/images/venues/sh7_3.jpg'],
  su1: ['/images/venues/su1_1.jpg', '/images/venues/su1_2.jpg', '/images/venues/su1_3.jpg'],
  sy1: ['/images/venues/sy1_1.jpg', '/images/venues/sy1_2.jpg', '/images/venues/sy1_3.jpg'],
  sz1: ['/images/venues/sz1_1.jpg', '/images/venues/sz1_2.jpg', '/images/venues/sz1_3.jpg'],
  sz2: ['/images/venues/sz2_1.jpg', '/images/venues/sz2_3.jpg'],
  sz3: ['/images/venues/sz3_1.jpg'],
  sz4: ['/images/venues/sz4_1.jpg', '/images/venues/sz4_2.jpg', '/images/venues/sz4_3.jpg'],
  sz5: ['/images/venues/sz5_1.jpg', '/images/venues/sz5_2.jpg'],
  tj1: ['/images/venues/tj1_1.jpg', '/images/venues/tj1_3.jpg'],
  tj2: ['/images/venues/tj2_1.jpg'],
  tj3: ['/images/venues/tj3_2.jpg', '/images/venues/tj3_3.jpg'],
  wh1: ['/images/venues/wh1_1.jpg', '/images/venues/wh1_2.jpg'],
  wh2: ['/images/venues/wh2_2.jpg', '/images/venues/wh2_3.jpg'],
  wh3: ['/images/venues/wh3_3.jpg'],
  xa2: ['/images/venues/xa2_1.jpg', '/images/venues/xa2_2.jpg', '/images/venues/xa2_3.jpg'],
  xa3: ['/images/venues/xa3_2.jpg', '/images/venues/xa3_3.jpg'],
  xm1: ['/images/venues/xm1_1.jpg', '/images/venues/xm1_3.jpg'],
  xm2: ['/images/venues/xm2_1.jpg', '/images/venues/xm2_2.jpg', '/images/venues/xm2_3.jpg'],
  zz1: ['/images/venues/zz1_2.jpg'],
  zz2: ['/images/venues/zz2_2.jpg'],
};
